export const TW_CLASS = {
  BADGE_XS: 'inline-flex items-center justify-center w-4 h-4 text-xs font-semibold text-blue-800 bg-blue-200 rounded-full ms-2',
  BADGE_SM: 'rounded-sm bg-gray-100 dark:bg-gray-700 py-0.5 px-3 border border-transparent font-medium text-xs text-gray-700 dark:text-gray-300 transition-colors shadow-sm',
  BADGE: 'rounded-sm bg-gray-100 dark:bg-gray-700 py-0.5 px-3 border border-transparent font-medium text-sm text-gray-700 dark:text-gray-300 transition-colors shadow-sm',
  BADGE_LG: 'px-3 py-1 text-sm transition-colors border-transparent rounded-sm shadow-sm text-gray-600 dark:text-gray-300 bg-gray-100 dark:bg-gray-700',
  BADGE_PRIMARY: 'text-sm transition-colors border-transparent rounded-sm shadow-sm text-primary-600 dark:text-primary-300 bg-primary-100 dark:bg-gray-700 dark:border-primary-300 text-center',
  BADGE_GRAY: 'text-sm transition-colors border-transparent rounded-sm shadow-sm text-gray-600 dark:text-gray-300 bg-gray-100 dark:bg-gray-700 dark:border-gray-300 text-center',
  BADGE_RED: 'text-sm transition-colors border-transparent rounded-sm shadow-sm !text-red-600 dark:text-red-300 !bg-red-100 dark:bg-gray-700 dark:border-red-300 text-center',
  BADGE_YELLOW: 'text-sm transition-colors border-transparent rounded-sm shadow-sm text-yellow-600 dark:text-yellow-300 bg-yellow-100 dark:bg-gray-700 dark:border-yellow-300 text-center',
  BADGE_GREEN: 'text-sm transition-colors border-transparent rounded-sm shadow-sm text-green-600 dark:text-green-300 bg-green-100 dark:bg-gray-700 dark:border-green-300 text-center',
  BADGE_PINK: 'text-sm transition-colors border-transparent rounded-sm shadow-sm text-pink-600 dark:text-pink-300 bg-pink-100 dark:bg-gray-700 dark:border-pink-300 text-center',
  BADGE_PURPLE: 'text-sm transition-colors border-transparent rounded-sm shadow-sm text-purple-600 dark:text-purple-300 bg-purple-100 dark:bg-gray-700 dark:border-purple-300 text-center ',
  BADGE_INDIGO:'text-sm transition-colors border-transparent rounded-sm shadow-sm text-indigo-800 dark:text-indigo-300 bg-indigo-100 dark:bg-gray-700 dark:border-indigo-300 text-center',
  BADGE_ICON: 'inline-flex items-center justify-center gap-1.5 text-sm py-1 px-2.5 rounded-sm w-max text-gray-700 dark:text-gray-300 bg-gray-100 dark:bg-gray-700',
  BADGE_ICON_ONLY: 'inline-flex items-center justify-center text-sm font-semibold rounded-sm w-7 h-7 text-gray-700 dark:text-gray-300 bg-gray-100 dark:bg-gray-700',
  BADGE_BTN: 'text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 focus:outline-none relative rounded-md flex bg-gray-100 dark:bg-gray-700 py-0.5 pl-2.5 pr-8 border border-transparent dark:border-gray-500 text-secondary-700 transition-colors shadow-sm',
  BADGE_BTN_OUTLINED: 'bg-transparent border-blue-700 text-blue-700 hover:bg-blue-800 hover:text-blue-50 focus:ring-4 focus:ring-blue-300 font-medium text-sm px-5 focus:outline-none relative rounded-md flex py-0.5 pl-2.5 pr-8 border transition-colors shadow-sm',
  BADGE_STATE_GREEN: 'rounded-sm flex items-center bg-green-100 dark:bg-gray-700 py-0.5 px-2.5 border border-transparent dark:border-green-300 text-sm text-green-800 dark:text-green-300 transition-colors shadow-sm',
  BADGE_STATE_RED: 'rounded-sm flex items-center bg-red-100 dark:bg-gray-700 py-0.5 px-2.5 border border-transparent dark:border-red-300 text-sm text-red-800 dark:text-red-300 transition-colors shadow-sm',
  BADGE_STATE_ICON_GREEN: 'block w-2 h-2 mx-auto mr-2 rounded-sm bg-green-800',
  BADGE_STATE_ICON_RED: 'block w-2 h-2 mx-auto mr-2 rounded-sm bg-red-800',
}
